poem_dic = {
    "data": [
        {
            "title": "Mindful of Fright",
            "date": "19-Feb-2024",
            "content": [
                "All my grim fears win over my night \n",
                "Now reveling in mind, showing\n",
                "me, jumping from height \n",
                "me, losing the one I hold tight \n",
                "me, being buried without light \n",
                "me, lost in the deepest of me \n",
                "\n",  # Add an empty line for better formatting
                "Those vicious made me eye, \n",
                "The I, I fear \n",
                "The scene, I averse \n",
                "The life, I distaste \n",
                "The person, I am \n",
                "Still, whom to blame",
            ],
            "meaning": "",
        },
        {
            "title": "Try",
            "date": "4-Feb-2024",
            "content": [
                "It's funny,\n",
                "Either you rely or maybe try\n",
                "Both lead to cry,\n",
                "Fact that I lack try\n",
                "Makes a hard cry\n",
                "But i try to try\n",
                "To be at the high\n",
                "Be in the greatest of air\n",
                "where I don't rely\n",
                # Add a marker for poem 2
            ],
            "meaning": "",
        },
        {
            "title": "Past, Present, Future…",
            "date": "10-Oct-2022",
            "content": [
                "The girl laid in her bed mellow,\n",
                "Thinking of the boy in yellow,\n",
                "“Was she eager about him?”,\n",
                "Thought she all night till brim.\n",
                "\n",  # Add an empty line for better formatting
                "It’s the boy now in his bed, lil’ mad,\n",
                "Feeling a little sad,\n",
                "Got no idea what’s happening,\n",
                "Thinking, the life’s blackening.\n",
                "\n",
                "Something’s going to happen,\n",
                "Maybe there gap going to dampen,\n",
                "The rest is upon you to decide,\n",
                "Make choices that are wise.",
            ],
            "meaning": "",
        },
        {
            "title": "I",
            "date": "11-Nov-2022",
            "content": [
                "I am not what I was, \n",
                "I am what I am, \n",
                "I hope to be a better I, \n",
                "And believe me, \n",
                " I will be. ",  # Note the extra space before "I will be" is preserved
            ],
            "meaning": "",
        },
        {
            "title": "Ocean Green",
            "date": "10-Sep-2022",
            "content": [
                "By the Blue Sea,\n",
                "He see,\n",
                "The ocean green,\n",
                "With gloom.\n",
                "\n",  # Add an empty line for better formatting
                "A thought struck him,\n",
                "“Why The Ocean’s not blue,\n",
                "But green?”,\n",
                "Said he.\n",
                "\n",
                "Near, a person can be seen,\n",
                "He said,\n",
                "It’s not green ,\n",
                "But corrupted by human bein’.",
            ],
            "meaning": "",
        },
        {
            "title": "The Things People Say (2AM talk)",
            "date": "13-Mar-2024",
            "content": [
                "they find the art in my mere life\n",
                "its me living and writing what I fright\n",
                "sometimes I notice the intricacies\n",
                "most of the time it isn't bright\n",
                "I hate to share it all, that's why,\n",
                "poetry is what I hide behind",
            ],
            "meaning": "",
        },
        {
            "title": "Mind Prison",
            "date": "13-Mar-2024",
            "content": [
                "The grandeur palace I hold\n",
                "Library with thousand memories\n",
                "The Tower where I gaze from\n",
                "The orchid which solace bright\n",
                "the fount of feelings I masoned\n",
                "By the fireflies I dreamt of flight.\n",
                "\n",  # Add an empty line for better formatting
                "all its beauty faded, went in ruins\n",
                "Its a prison, me being the incell\n",
                "by the heartless warden I am\n",
                "the aperture in my cell, I watch the fount red\n",
                "No judge, no jury, this sentence mine,\n",
                "Freedom's a quest, a distant sign.",
            ],
            "meaning": "",
        },
        {
            "title": "The Night I Went on A Stroll",
            "date": "2-Mar-2024",
            "content": [
                "yesternight I went on a stroll\n",
                "with me was the spirit of yours\n",
                "we had a lot of talk\n",
                "I got all the answers I wonder for\n",
                "you told me I am the desperate one\n",
                "You told me you hate it with me\n",
                "You dont wanna talk,\n",
                "\n",  # Add an empty line for better formatting
                "I took it as sarcasm\n",
                "I told everything I hold you account for\n",
                "Its just that you changed me a lot\n",
                "Its not only you\n",
                "who left me all alone\n",
                "We talked about the night we star-gazed\n",
                "but honestly I was just looking at you all along\n",
                "\n",
                "Hints you gave me laying,\n",
                "then said it was nothing\n",
                "lying is what you did at all\n",
                "It was happy being with you\n",
                "I am the one who got it all wrong\n",
                "I wanna focus now not fight\n",
                "Bye-Bye and good night",
            ],
            "meaning": "",
        },
        {
            "title": "My Travel Story",
            "date": "4-Feb-2024",
            "content": [
                "Stuck in a loop\n",
                "Living the same week\n",
                "Like a hoop\n",
                "Night’s a oxymoron\n",
                "Loves hating it\n",
                "Feels like an moron\n",
                "\n",  # Add an empty line for better formatting
                "Spent hours contemplating\n",
                "Kill me or not\n",
                "Can’t care less\n",
                "Haven’t Seen a lot\n",
                "\n",
                "The last I felt something\n",
                "Was a nightmare I dreamed of\n",
                "Feels like a helpmate\n",
                "In story of my own\n",
                "\n",
                "Want to break the time machine\n",
                "To get a way out the loop\n",
                "it must end with a snap\n",
                "And the climax needs to be a clap ",
            ],
            "meaning": "",
        },
        {
            "title": "The Mytique Watch",
            "date": "4-Mar-2024",
            "content": [
                "The time I watched my watch on the bus\n",
                "I saw a window in it with a hole,\n",
                "once I blinked I saw her\n",
                "giving me birth\n",
                "he was crying, they both hugged\n",
                "\n",  # Add an empty line for better formatting
                "I blinked once more\n",
                "I saw her dressing me for the day\n",
                "I saw him clicking pictures\n",
                "and making me smile\n",
                "it all went for a while\n",
                "\n",
                "I blinked again\n",
                "now I can't see her or him\n",
                "but what I saw gave me cries\n",
                "it was a divine beauty\n",
                "which gave butterflies\n",
                "\n",
                "I blinked for the fourth\n",
                "It was all black\n",
                "I remember!\n",
                "it was my birthday in september\n",
                "they gave me a surprise made of lumber\n",
                "\n",
                "I wish to blink more, but scared to know\n",
                "if it holds any good to me\n",
                "If I recall, it's where the obscene episode is\n",
                "the one which I don't wanna remember\n",
                "its my stop now I should leave",
            ],
            "meaning": "",
        },
        {
            "title": "Chances Not Taken",
            "date": "3-Feb-2024",
            "content": [
                "Standing at the convergence,\n",
                'Should I take "the road not taken"\n',
                "Or the one striding,\n",
                "Is it me only,\n",
                "Or are you too musing,\n",
                "What obscurity is the one not taken hold.\n",
                "\n",  # Add an empty line for better formatting
                "The chance taken was the striding,\n",
                "But in my mind I took the lurking one,\n",
                "I took what was destined,\n",
                "But what matters is,\n",
                "What I missed,",
            ],
            "meaning": "",
        },
        {
            "title": "Natural Actor",
            "date": "9-Feb-2024",
            "content": [
                "Those ruthless nights\n",
                "Those fake smiles\n",
                "Those nightless gelling\n",
                "Those lifeless dwelling,\n",
                "\n",  # Add an empty line for better formatting
                "It's all a setup\n",
                "It's not who I am\n",
                "It's all an act\n",
                "It's not what's natural.",
            ],
            "meaning": "",
        },
        {
            "title": "A Friend Who Made me Blush",
            "date": "2-Mar-2024",
            "content": [
                "all the scenes in my mind\n",
                "your, face's blush makes me remind,\n",
                "all the curses in my verses\n",
                "the bad time i had,\n",
                "'am now happy it was sad.\n",
                "\n",  # Add an empty line for better formatting
                "not used to all this love\n",
                "but it feels like a trust-o-shove,\n",
                "the first compliment I got\n",
                "wasn't from the one I hoped\n",
                "but talking to you makes me sane\n",
                "or I guess I was never Insane",
            ],
            "meaning": "",
        },
        {
            "title": "Feelings",
            "date": "1-Mar-2024",
            "content": [
                "The day she came,\n",
                "Wasn't planned at all\n",
                "The fate we share,\n",
                "Wasn't the one I destined for\n",
                "\n",  # Add an empty line for better formatting
                "The feelings I had,\n",
                "Was something I never told\n",
                "\n",
                "It's the banter,\n",
                'which is left with "doré"\n',
                "Truth then exchanged,\n",
                "was it the one I was hoping for?\n",
                "\n",
                "This ain't a dream,\n",
                "Wish it was\n",
                "\n",
                "The button isn't present here,\n",
                'it\'s the "undo" I wanna pop\n',
                "In our eyes it came to a halt,\n",
                "it's where I am stuck too\n",
                "\n",
                "The sorries I never said,\n",
                "Are still here, roams in my head\n",
                "\n",
                "The regrets I have,\n",
                "Are still on the list waiting to be checked\n",
                "The things I blame myself for,\n",
                "Are the one others made me own",
            ],
            "meaning": "",
        },
        {
            "title": "Shy",
            "date": "6-Feb-2024",
            "content": [
                "I wanna' express it,\n",
                "Not be unheard and not be unlit.\n",
                "\n",  # Add an empty line for better formatting
                "Last time I remember,\n",
                "the starry glory of November.\n",
                "\n",
                "She was waiting for me to speak,\n",
                "But only if I could have opened my beak.",
            ],
            "meaning": "",
        },
    ]
}
